### ISSUE TITLE
Adding documentation for setting up Google Analytics and Facebook Comments

### ISSUE THREAD

**Issue by marcelkooi** [greglobinski/gatsby-starter-kit-docs#2]
I'm not sure where this should live, but I think there should be a section that mentions you should set environment variables for `GOOGLE_ANALYTICS_ID` and `GATSBY_FACEBOOK_APPID` if you want to use Google Analytics and Facebook Comments, respectively.

**Comment by greglobinski** [comment]
@marcelkooi 
Yup, and it's not the only one thing which should be in the docs already but it's not :). 
I think that because it's common for many of the starters it should be in **Guides** as a separate article.
If you are willing to help, send PR
